# --- Created by Slick DDL


# --- !Ups

create table `FAVOURITE` (`FAVOURITE_NAME` VARCHAR(254) NOT NULL,`FAVOURITE_ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY);
create table `MOVIE` (`THE_MOVIE_DB_ID` INTEGER NOT NULL,`FAVOURITE_ID` INTEGER NOT NULL,`MOVIE_NAME` VARCHAR(254) NOT NULL,`ID` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY);
alter table `MOVIE` add constraint `FAVOURITE_ID` foreign key(`FAVOURITE_ID`) references `FAVOURITE`(`FAVOURITE_ID`) on delete CASCADE;




